# Rubocop comes with most cops enabled and some disabled by default.
# Our style guide does not match these defaults, so we explicitly enable/disable some cops below.

AbcSize:
  Enabled: false

AccessorMethodName:
  Enabled: false

AlignArray:
  Enabled: false

AlignHash:
  Enabled: false

AlignParameters:
  Enabled: false

AmbiguousOperator:
  Enabled: false

AmbiguousRegexpLiteral:
  Enabled: false

AssignmentInCondition:
  Enabled: false

CaseIndentation:
  IndentWhenRelativeTo: end

ClassAndModuleChildren:
  Enabled: false

ClassLength:
  Enabled: false

CollectionMethods:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

Delegate:
  Enabled: false

Documentation:
  Enabled: false

DotPosition:
  EnforcedStyle: leading
  Enabled: false

DoubleNegation:
  Enabled: false

EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

EndAlignment:
  AlignWith: variable

FormatString:
  EnforcedStyle: percent

GuardClause:
  Enabled: false

HandleExceptions:
  Enabled: false

HasAndBelongsToMany:
  Enabled: false

IfUnlessModifier:
  Enabled: false

IndentHash:
  Enabled: false

IndentationWidth:
  Enabled: false

Lambda:
  Enabled: false

LineLength:
  Max: 100

Loop:
  Enabled: false

MethodCalledOnDoEndBlock:
  Enabled: false

MethodLength:
  Enabled: false

MultilineOperationIndentation:
  Enabled: false

Next:
  Enabled: false

NumericLiterals:
  Enabled: false

ParameterLists:
  Enabled: false

ParenthesesAsGroupedExpression:
  Enabled: false

PerceivedComplexity:
  Enabled: false

PredicateName:
  Enabled: false

RegexpLiteral:
  Enabled: false

RescueModifier:
  Enabled: false

SignalException:
  Enabled: false

SpaceAfterColon:
  Enabled: false

TrivialAccessors:
  Enabled: false

UnusedBlockArgument:
  Enabled: false

UnusedMethodArgument:
  Enabled: false

UselessAssignment:
  Enabled: false

Validation:
  Enabled: false

# Can be enabled when we switch to RSpec "expect.to" syntax:
Void:
  Enabled: false

WhileUntilModifier:
  Enabled: false

WordArray:
  MinSize: 3
