module Levelup
  module Errors
    # An error generated by the LevelUp client when the user attempts a request
    # that is in some way of invalid format.
    class InvalidRequest < StandardError
    end
  end
end
