module Levelup
  module Errors
    # An error generated by the LevelUp client when the user attempts to
    # perform an authorized action without an access token.
    class Unauthenticated < StandardError
    end
  end
end
